# Created by: WestleyR
# email: westleyr@nym.hush.com
# Date: Feb 7, 2018
# https://github.com/WestleyR/print-line
# Version-1.0.3
#
# The Clear BSD License
#
# Copyright (c) 2019 WestleyR
# All rights reserved.
#
# This software is licensed under a Clear BSD License.
#
# This Makefile was generated by: configure, and was:
#  generated in      : /home/westley/new-repo/print-line
#  generated by      : westley
#  generated on      : February 08, 2019, 05:49:30 PM
#  generated on arch : x86_64
#
#
# DO NOT EDIT!
#


PREFIX = /usr/bin
CODE_NAME = main-print-line.c
SCRIPT_NAME = pl
INFO_NAME = func_info.c
GEN_SCRIPT = gen_info.sh

COMPILER = gcc

CFLAG = -std=c99
STATIC_BUILD_FLAG = -static
FLAG = 

.PHONY:
all: $(CODE_NAME)
	chmod +x $(GEN_SCRIPT)
	./$(GEN_SCRIPT)
	$(COMPILER) $(FLAG) $(CFLAG) -o $(SCRIPT_NAME) $(CODE_NAME) $(INFO_NAME)
	@rm -f $(INFO_NAME)
	@echo
	@echo "Done."
	@echo ">> Do:"
	@echo "  $$ sudo make install"

.PHONY:
static: $(CODE_NAME)
	chmod +x $(GEN_SCRIPT)
	./$(GEN_SCRIPT)
	$(COMPILER) $(FLAG) $(CFLAG) $(STATIC_BUILD_FLAG) -o $(SCRIPT_NAME) $(CODE_NAME) $(INFO_NAME)
	rm -f $(INFO_NAME)
	@echo
	@echo "Done."
	@echo ">> Do:"
	@echo "  $$ sudo make install"

.PHONY:
install: $(SCRIPT_NAME)
	@echo "installing to: $(PREFIX)"
	chmod +x $(SCRIPT_NAME)
	cp -f $(SCRIPT_NAME) $(PREFIX)

.PHONY:
clean:
	rm -f $(SCRIPT_NAME)
	rm -f $(INFO_NAME)

.PHONY:
uninstall: $(PREFIX)/$(SCRIPT_NAME)
	@echo "Uninstalling: $(SCRIPT_NAME), from: $(PREFIX)..."
	rm -f $(PREFIX)/$(SCRIPT_NAME)
